export const FETCH_LIST_OF_USERS_REQUEST = 'FETCH_LIST_OF_USERS_REQUEST';
export const FETCH_LIST_OF_USERS_SUCCESS = 'FETCH_LIST_OF_USERS_SUCCESS';
export const FETCH_LIST_OF_USERS_FAILURE = 'FETCH_LIST_OF_USERS_FAILURE';

export const FETCH_USER_REQUEST = "FETCH_USER_REQUEST"
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS"
export const FETCH_USER_FAILURE = "FETCH_USER_FAILURE"
